### ISSUE TITLE
Нужен токен из ВК?

### ISSUE THREAD

**Issue by domik25** [dogekiller21/ViKtor_Music_Bot#2]
Нужен токен из ВК? 
Немного не понимаю, но знаю что он должен быть где-то здесь? - 
![image](https://user-images.githubusercontent.com/96686759/221376083-a2708a3b-5214-4bbe-a030-d539057864a0.png)

**Comment by dogekiller21** [comment]
Токен можно [**тут**](https://vkhost.github.io/) получить
Подходит токен от Маруси (нужен с доступом к аудио)

**Comment by domik25** [comment]
А что делать с 
![image](https://user-images.githubusercontent.com/96686759/221377810-a7de1517-7acc-4079-b43d-372f125d785e.png)

ошибкой? -

**Comment by domik25** [comment]
AttributeError: module 'discord' has no attribute 'Bot' хм....

**Comment by domik25** [comment]
![image](https://user-images.githubusercontent.com/96686759/221380353-6538e351-c5a0-485a-86e1-9781ed839c4a.png)
Хм...?

**Comment by dogekiller21** [comment]
1. Какая версия питона используется?
2. Пакеты устанавливались с помощью 'pip install -r requirements.txt' ?

**Comment by domik25** [comment]
Писал про пакеты, версия последняя
А discord py 1.7.3

**Comment by domik25** [comment]
![image](https://user-images.githubusercontent.com/96686759/221382808-3402af5a-48cf-43e5-96d4-b7b5119bb0d4.png)
Переустановил все что мог

**Comment by dogekiller21** [comment]
Версия python 3.10 нужна
На 3.11 некоторые модули еще не работает

Советую использовать виртуальное окружение, например, стандартный для питона venv
**python -m venv venv**

Для активации окружения:
- Для windows **venv/Scripts/activate.bat**
- Для linux source **venv/bin/activate**

После этого уже используя **pip install -r requirements.txt** устанавливаем все пакеты

Должно помочь :)

**Comment by domik25** [comment]
![image](https://user-images.githubusercontent.com/96686759/221395046-877418aa-620c-4a7d-9cbc-be619a9bb788.png)
Ошибки ошибки... При попытке установить dotenv

**Comment by dogekiller21** [comment]
Модуль называется `python-dotenv`, не просто **dotenv**

**Comment by domik25** [comment]
не понял немного :D

**Comment by dogekiller21** [comment]
`pip install python-dotenv`

**Comment by domik25** [comment]
Писал, не помогло :D

**Comment by domik25** [comment]
Ошибки и ошибки.. Господи, я просто хотел создать бота, а не ломать голову

**Comment by dogekiller21** [comment]
Жаль, что не оправдал твои ожидания :)

Последнее, что может помочь - обновить `pip` до версии **22.3.1** с помощью `pip install --upgrade pip==22.3.1`
