### ISSUE TITLE
Невозможно использовать команды бота

### ISSUE THREAD

**Issue by fagirton** [dogekiller21/ViKtor_Music_Bot#4]
Установил и запустил бота в Docker'е, натравил на бота, который уже есть на сервере, но бот не отвечает ни на одну команду, вместо этого появляется автокоррекция других ботов. Пробовал приглашать бота на сервер с другими scopes (в readme написано, что нужен bot и application.commands), но ничего не помогает.
Как я понял у бота должен быть значок "Поддерживаются команды" и автокоррекция команд после /

**Comment by dogekiller21** [comment]
Все верно поняли. Команды могут появиться не сразу.

**Comment by fagirton** [comment]
То есть они появляются чуть позже? 
И сколько тогда обычно нужно ждать? И надо ли держать бота включенным?

**Comment by dogekiller21** [comment]
Можешь подробнее почитать про команды тут -> https://discord.com/developers/docs/interactions/application-commands
