### ISSUE TITLE
Ошибка, вроде связанная с bot-bot-1

### ISSUE THREAD

**Issue by Adovka** [dogekiller21/ViKtor_Music_Bot#5]
Здравствуйте , я оч. ламер, так что прошу прощения за трату вашего времени

У меня появилась проблема с ботом, запускал через докер. Бот входит в сеть, но нет команд. Ошибок в логах не было, но я решил подождать и всё-таки одна вылезла, правда я вообще не могу её понять

viktor_music_bot-db-1   | 2023-07-26 10:00:11.961 UTC [1] LOG:  database system is ready to accept connections
viktor_music_bot-bot-1  |     tr, pr = await compat.wait_for(connector, timeout=timeout)
viktor_music_bot-bot-1  |   File "/usr/local/lib/python3.10/site-packages/asyncpg/compat.py", line 56, in wait_for
viktor_music_bot-bot-1  |     return await asyncio.wait_for(fut, timeout)
viktor_music_bot-bot-1  |   File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
viktor_music_bot-bot-1  |     return fut.result()
viktor_music_bot-bot-1  |   File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 684, in _create_ssl_connection
viktor_music_bot-bot-1  |     tr, pr = await loop.create_connection(
viktor_music_bot-bot-1  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
viktor_music_bot-bot-1  |     raise exceptions[0]
viktor_music_bot-bot-1  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
viktor_music_bot-bot-1  |     sock = await self._connect_sock(
viktor_music_bot-bot-1  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
viktor_music_bot-bot-1  |     await self.sock_connect(sock, address)
viktor_music_bot-bot-1  |   File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
viktor_music_bot-bot-1  |     return await fut
viktor_music_bot-bot-1  |   File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
viktor_music_bot-bot-1  |     raise OSError(err, f'Connect call failed {address}')
viktor_music_bot-bot-1  | ConnectionRefusedError: [Errno 111] Connect call failed ('172.22.0.2', 5432)
viktor_music_bot-bot-1  | 2023-07-26 10:00:15,406:INFO:discord.client: logging in using static token
viktor_music_bot-bot-1  | 2023-07-26 10:00:17,180:INFO:discord.gateway: Shard ID None has sent the IDENTIFY payload.
viktor_music_bot-bot-1  | 2023-07-26 10:00:17,791:INFO:discord.gateway: Shard ID None has connected to Gateway: ["gateway-prd-us-east1-c-x9r8",{"micros":207526,"calls":["id_created",{"micros":955,"calls":[]},"session_lookup_time",{"micros":267,"calls":[]},"session_lookup_finished",{"micros":12,"calls":[]},"discord-sessions-prd-2-266",{"micros":205721,"calls":["start_session",{"micros":134438,"calls":["discord-api-787dffbb67-kt7jb",{"micros":93840,"calls":["get_user",{"micros":18109},"get_guilds",{"micros":5551},"send_scheduled_deletion_message",{"micros":12},"guild_join_requests",{"micros":294},"authorized_ip_coro",{"micros":14}]}]},"starting_guild_connect",{"micros":52,"calls":[]},"presence_started",{"micros":27677,"calls":[]},"guilds_started",{"micros":74,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":43431,"calls":[]},"connect_finished",{"micros":43435,"calls":[]},"build_ready",{"micros":19,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":23,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: b2905bc16dd1039d3530a2896097c358).
viktor_music_bot-bot-1  | Ignoring exception in on_connect
viktor_music_bot-bot-1  | Traceback (most recent call last):
viktor_music_bot-bot-1  |   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 378, in _run_event
viktor_music_bot-bot-1  |     await coro(*args, **kwargs)
viktor_music_bot-bot-1  |   File "/usr/local/lib/python3.10/site-packages/discord/bot.py", line 1164, in on_connect
viktor_music_bot-bot-1  |     await self.sync_commands()
viktor_music_bot-bot-1  |   File "/usr/local/lib/python3.10/site-packages/discord/bot.py", line 738, in sync_commands
viktor_music_bot-bot-1  |     app_cmds = await self.register_commands(
viktor_music_bot-bot-1  |   File "/usr/local/lib/python3.10/site-packages/discord/bot.py", line 531, in register_commands
viktor_music_bot-bot-1  |     prefetched_commands = await self._bot.http.get_guild_commands(
viktor_music_bot-bot-1  |   File "/usr/local/lib/python3.10/site-packages/discord/http.py", line 365, in request
viktor_music_bot-bot-1  |     raise Forbidden(response, data)
viktor_music_bot-bot-1  | discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
viktor_music_bot-bot-1  | 2023-07-26 10:00:19,798:INFO:root: We have logged in as GLEB#1108
viktor_music_bot-bot-1  | 2023-07-26 10:04:02,367:INFO:discord.gateway: Websocket closed with WSCloseCode.ABNORMAL_CLOSURE, attempting a reconnect.
viktor_music_bot-bot-1  | 2023-07-26 10:04:02,367:INFO:discord.client: Got a request to RESUME the websocket.
viktor_music_bot-bot-1  | 2023-07-26 10:04:03,047:INFO:discord.gateway: Shard ID None has sent the RESUME payload.
viktor_music_bot-bot-1  | 2023-07-26 10:04:03,246:INFO:discord.gateway: Shard ID None has successfully RESUMED session b2905bc16dd1039d3530a2896097c358 under trace ["gateway-prd-us-east1-c-770s",{"micros":1820,"calls":["id_created",{"micros":0,"calls":[]},"session_lookup_time",{"micros":1583,"calls":[]},"session_lookup_finished",{"micros":14,"calls":[]},"discord-sessions-prd-2-266",{"micros":22}]}].

Я что-то не так сделал или чего-то не сделал?

**Comment by dogekiller21** [comment]
Извини за долгий ответ
Похоже, что у тебя не валидный токен внутри енва)
Перепроверь все по гайду из readme

На текущий момент нет времени заниматься проектом, забросил его давненько
Если будут какие-то ошибки, вряд ли смогу быстро помочь
Кидаю репу в архив на текущий момент
